/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package api.de.nomes.view;

import api.de.nomes.control.ControlerMainFrame;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import org.json.simple.parser.ParseException;

/**
 *
 * @author khayzer
 */
public class FormRank extends javax.swing.JPanel {

    public ControlerMainFrame control;

    public FormRank(ControlerMainFrame control) {
        initComponents();
        this.control = control;
    }

    public ControlerMainFrame getControl() {
        return control;
    }

    public void setControl(ControlerMainFrame control) {
        this.control = control;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public void setBotaoVoltar(JButton botaoVoltar) {
        this.botaoVoltar = botaoVoltar;
    }

    public JButton getBotaobuscar() {
        return botaobuscar;
    }

    public void setBotaobuscar(JButton botaobuscar) {
        this.botaobuscar = botaobuscar;
    }

    public JLabel getLabeldecada() {
        return labeldecada;
    }

    public void setLabeldecada(JLabel labeldecada) {
        this.labeldecada = labeldecada;
    }

    public JLabel getLabellocalidade() {
        return labellocalidade;
    }

    public void setLabellocalidade(JLabel labellocalidade) {
        this.labellocalidade = labellocalidade;
    }

    public JLabel getLabelsexo() {
        return labelsexo;
    }

    public void setLabelsexo(JLabel labelsexo) {
        this.labelsexo = labelsexo;
    }

    public JTextField getTextdecada() {
        return textdecada;
    }

    public void setTextdecada(JTextField textdecada) {
        this.textdecada = textdecada;
    }

    public JTextField getTextlocalidade() {
        return textlocalidade;
    }

    public void setTextlocalidade(JTextField textlocalidade) {
        this.textlocalidade = textlocalidade;
    }

    public JTextField getTextsexo() {
        return textsexo;
    }

    public void setTextsexo(JTextField textsexo) {
        this.textsexo = textsexo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labeldecada = new javax.swing.JLabel();
        labellocalidade = new javax.swing.JLabel();
        labelsexo = new javax.swing.JLabel();
        textdecada = new javax.swing.JTextField();
        textlocalidade = new javax.swing.JTextField();
        textsexo = new javax.swing.JTextField();
        botaobuscar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        labeldecada.setText("Decada:");

        labellocalidade.setText("Localidade:");

        labelsexo.setText("Sexo:");

        textlocalidade.setText("BR");
        textlocalidade.setEnabled(false);

        botaobuscar.setText("Buscar");
        botaobuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaobuscarActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labeldecada)
                                .addGap(30, 30, 30)
                                .addComponent(textdecada, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labellocalidade)
                                    .addComponent(labelsexo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textlocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(botaoVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaobuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldecada)
                    .addComponent(textdecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labellocalidade)
                    .addComponent(textlocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelsexo)
                    .addComponent(textsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaobuscar)
                    .addComponent(botaoVoltar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.control.voltarRank();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaobuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaobuscarActionPerformed

        try {
            this.control.buscaRank();
        } catch (IOException ex) {
            System.out.println("io exception:"+evt.toString());
        } catch (ParseException ex) {
            System.out.println("parse exception:"+evt.toString());
        }

    }//GEN-LAST:event_botaobuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JButton botaobuscar;
    private javax.swing.JLabel labeldecada;
    private javax.swing.JLabel labellocalidade;
    private javax.swing.JLabel labelsexo;
    private javax.swing.JTextField textdecada;
    private javax.swing.JTextField textlocalidade;
    private javax.swing.JTextField textsexo;
    // End of variables declaration//GEN-END:variables
}
